# **31-Working with Matrix in Python**



https://www.youtube.com/watch?v=Blzp9iuhZqo&list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3&index=37


# **The reason for using NUMPY was MULTI DIMENSIONAL ARRAY.  **


# **For an regular arrays we can ARRAY function. **

In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

print(arr1)




[[1 2 3]
 [4 5 6]]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

print(arr1.dtype)


int64


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

print(arr1.ndim)


2


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

print(arr1.shape)


(2, 3)


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

print(arr1.size)


6


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

arr2= arr1.flatten()

print(arr2)
print(arr1)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

arr2= arr1.flatten()

print(arr2)



[1 2 3 4 5 6]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3,9,10],
              [4,5,6,18,45]

])

arr2= arr1.flatten()

print(arr2)


[ 1  2  3  9 10  4  5  6 18 45]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3,9,10],
              [4,5,6,18]

])

arr2= arr1.flatten()

print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
from array import *

arr1 = array([

              [1,2,3,9,10],
              [4,5,6,18,45]

])

arr2= arr1.flatten()

print(arr2)

TypeError: array() argument 1 must be a unicode character, not list

In [ ]:
from numpy import *

arr1 = array([

              [1,2,3,9,6,89],
              [4,5,6,18,45,86]

])

arr2= arr1.flatten()

arr3= arr2.reshape(3,4)

print(arr3)

[[ 1  2  3  9]
 [ 6 89  4  5]
 [ 6 18 45 86]]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3,9,6,89],
              [4,5,6,18,45,86]

])

arr2= arr1.flatten()

arr3= arr2.reshape(2,2,3)

print(arr3)


[[[ 1  2  3]
  [ 9  6 89]]

 [[ 4  5  6]
  [18 45 86]]]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

m=matrix(arr1)

print(m)


[[1 2 3]
 [4 5 6]]


In [ ]:
from numpy import *

arr1 = array([

              [1,2,3],
              [4,5,6]

])

m=matrix('1 2 3 6; 4 5 8 9')

print(m)


[[1 2 3 6]
 [4 5 8 9]]


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9')

print(m)


[[1 2 3 6]
 [4 5 8 9]]


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9; 74,52,8,966')

print(m)

[[  1   2   3   6]
 [  4   5   8   9]
 [ 74  52   8 966]]


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9; 74,52,8,966')

print(diagonal(m))

[1 5 8]


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9; 74,52,8,966')

print(m.min())

1


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9; 74,52,8,966')

print(m.max())

966


In [ ]:
from numpy import *


m=matrix('1 2 3 6; 4 5 8 9; 74,52,8,966')

print(m.sum())

1138


In [ ]:
from numpy import *


m1=matrix('1 2; 4 5')

m2=matrix('1 2; 4 5')
m3=m1*m2;

print(m3)

[[ 9 12]
 [24 33]]


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1*m2;

print(m3)

[[ 41  68  36]
 [ 60  96  52]
 [301 445 360]]


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1*m2

print(m3)

[[ 41  68  36]
 [ 60  96  52]
 [301 445 360]]


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1+m2

print(m3)

[[ 2  4 12]
 [ 8 10  9]
 [93 59  5]]


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1-m2

print(m3)

[[ 0  0  4]
 [ 0  0  9]
 [85 45 -3]]


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1/m2

print(m3)

[[ 1.          1.          2.        ]
 [ 1.          1.                 inf]
 [22.25        7.42857143  0.25      ]]


/tmp/ipython-input-2818745806.py:7: RuntimeWarning: divide by zero encountered in divide
  m3=m1/m2


In [ ]:
from numpy import *


m1=matrix('1 2 8; 4 5 9; 89 52 1')

m2=matrix('1 2 4; 4 5 0; 4 7 4')
m3=m1%m2

print(m3)

[[0 0 0]
 [0 0 0]
 [1 3 1]]


/tmp/ipython-input-1963818252.py:7: RuntimeWarning: divide by zero encountered in remainder
  m3=m1%m2
